### ISSUE TITLE
Multitrack Recording Button

### ISSUE THREAD

**Issue by seany** [ZerGo0/streamdeck-teamspeak3integration#11]
Heyo! I've been using this plugin a lot recently, and it's proved to be really useful. Not sure if it's still being updated, but a feature that would be super useful would be the ability to start/stop recording/multitrack recording with a button. It would make my workflow so much easier if I could use this in a multi-action with OBS. Appreciate it!

**Comment by ZerGo0** [comment]
Hey, I'm glad that you like the plugin. I'm still maintaining it actively, but there are no functions that I could think of right now that would be crucial at least for me. That's why there hasn't been an update for a while.

From what I can see, it doesn't seem like it is possible. The ClientQuery has only limited functionality sadly and functions like this just never got added to it.

You can add a custom hotkey to Teamspeak and add the hotkey to your Streamdeck. It's not as fancy but should do the job just fine.
