### ISSUE TITLE
[ENHANCEMENT] Toogle local inpute mute

### ISSUE THREAD

**Issue by PythonInvasion** [ZerGo0/streamdeck-teamspeak3integration#2]
Hey. You can mute your microphon so everybody can see it.  But there is also an option/keybind to mute your microphon local.
It means you mute your microphon without any symbol/icon.

If you have further question - please answer below.

**Comment by ZerGo0** [comment]
Added in [v1.5](https://github.com/ZerGo0/streamdeck-teamspeak3integration/releases/tag/v1.5): 
- Added `Toggle INPUT (Local) Mute` Action which allows you to toggle the input mute status locally so that no one on the server can see it (Currently there is no dynamic way to update this status (couldn't find any public information about this), it will use the button state for now)
